version: '3.8'

services:
  db:
    image: postgres:18
    container_name: hostel-db
    environment:
      POSTGRES_DB: hostel_management_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "$$@nju#29" # Use your actual variable or secret
    volumes:
      - ./hostel_management_dump.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: hostel-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker